### ISSUE TITLE
Error while compiling crfasrnn code

### ISSUE THREAD

**Issue by mehtasachin** [torrvision/crfasrnn#16]
Hi,

I am trying to compile the code, but getting following error:

./lib/libcaffe.so: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
../lib/libcaffe.so: undefined reference to`testing::AssertionSuccess()'
../lib/libcaffe.so: undefined reference to `testing::Test::~Test()'
../lib/libcaffe.so: undefined reference to`testing::internal::IsTrue(bool)'
../lib/libcaffe.so: undefined reference to `typeinfo for testing::Test'
../lib/libcaffe.so: undefined reference to`testing::Test::SetUp()'
../lib/libcaffe.so: undefined reference to `testing::Test::TearDown()'
../lib/libcaffe.so: undefined reference to`testing::Test::Test()'
../lib/libcaffe.so: undefined reference to `testing::internal::String::Format(char const*, ...)'
../lib/libcaffe.so: undefined reference to`testing::internal::AssertHelper::~AssertHelper()'
../lib/libcaffe.so: undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
../lib/libcaffe.so: undefined reference to`testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const_, int, char const_)'
../lib/libcaffe.so: undefined reference to `testing::internal::EqFailure(char const_, char const_, testing::internal::String const&, testing::internal::String const&, bool)'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/caffe] Error 1
make[1]: **\* [tools/CMakeFiles/caffe.bin.dir/all] Error 2
make: **\* [all] Error 2

I am using Ubuntu 14.04 and followed the steps mentioned in the web page while installation.

It would be great if you can help me in resolving the error

Thanks.

P.S.: I tried to compile caffe and it worked successfully.

**Comment by bittnt** [comment]
@mehtasachin It seems you have not installed correct dependencies the customised caffe required. You should get it working with cuda 7.5/6.5, anaconda python 2.7x, intel MKL (or atlas), snappy, lmdb, leveldb, hdf5, protobuf, and etc. For more information, you should check caffe website.

If you have a successful compiled caffe version, simply copying the Makefile.config to the main path should do the job. But you should be aware that the caffe latest version is quite different from this customised caffe.

**Comment by mtourne** [comment]
@mehtasachin if you're having trouble compiling, I recommend trying out my fork which is reconciled with caffe upstream : https://github.com/mtourne/crfasrnn

In my experience it will compile more easily, especially if you're trying on mac os.

**Comment by mehtasachin** [comment]
@mtourne I tried your work. I am able to successfully compile it, but the model is not working. I looked at the layer structure in Caffe website to figure out the error and it seems that multiple layers have been removed or renamed (for instance, CROP). I didn't find any information on these changes. Could you please share your working prototxt file for code in shared link.

**Comment by rshvetsov** [comment]
It helped me to copy gtest sources (*.h, *.c* and etc ) to ../src/caffe/ and project was built ;)
